# Generated by Django 4.1.7 on 2023-05-03 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bd_app', '0002_datos_propiedad_model_direccion2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datos_propiedad_model',
            name='direccion2',
        ),
    ]
