# Generated by Django 4.1.7 on 2023-05-03 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bd_app', '0003_remove_datos_propiedad_model_direccion2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datos_propiedad_model',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
