# Generated by Django 4.1.7 on 2023-05-03 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bd_app', '0004_alter_datos_propiedad_model_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datos_propiedad_model',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
